apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mlflow-config
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  BACKEND_STORE_URI: >-
    postgresql+psycopg2://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql.{{ .Values.global.namespace }}.svc.cluster.local:5432/{{ .Values.postgresql.auth.database }}
  AWS_ACCESS_KEY_ID: "{{ .Values.minio.auth.rootUser }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.minio.auth.rootPassword }}"
  MLFLOW_S3_ENDPOINT_URL: "http://{{ .Release.Name }}-minio.{{ .Values.global.namespace }}.svc.cluster.local:9000"