{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.existingSecretName | quote }}
type: Opaque
stringData:
  IBMCLOUD_API_KEY: {{ .Values.secrets.IBMCLOUD_API_KEY | quote }}
  WATSONX_PROJECT_ID: {{ .Values.secrets.WATSONX_PROJECT_ID | quote }}
  WATSONX_API_URL: {{ .Values.secrets.WATSONX_API_URL | quote }}
  WATSONX_LLM_MODEL_ID: {{ .Values.secrets.WATSONX_LLM_MODEL_ID | quote }}
  WATSONX_EMBEDDING_MODEL_ID: {{ .Values.secrets.WATSONX_EMBEDDING_MODEL_ID | quote }}
{{- end }}